billapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('', include('transactions.urls')),
    path('inventory/', include('inventory.urls')),
    path('funds/', include('funds.urls')),
    path('sale/', include('bills.urls')),
    path('reports/', include('reports.urls')),
]

bills/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('retail/', views.SalesBillCreateView.as_view(), name='create_retail_view'),
    path('wholesale/', views.SalesBillCreateView.as_view(), name='create_wholesale_view'),
    path('<int:pk>/', views.SalesBillUpdateView.as_view(), name='edit_sale'),
    path('delete/<int:pk>/', views.SalesBillDeleteView.as_view(), name='delete_sale_view'),
    path('bills/', views.SalesBillListView.as_view(), name='list_sale_view'),
    path('bill/', views.bills, name='bills'),
    path('<int:bill_number>/thermal', views.thermal_sales_bill, name='thermal_sales_bill'),
    path('<int:bill_number>/full', views.full_sales_bill, name='full_sales_bill'),
    
]

inventory/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.

class StockType(models.Model):
    UNIT_CHOICES = [
        ('', 'None'),
        ('mtr', 'Meter'),
        ('ml', 'Milliliter'),
    ]

    name = models.CharField(max_length=100, unique=True)
    unit = models.CharField(max_length=3, choices=UNIT_CHOICES, default='')

    @property
    def no_of_stocks(self):
        return self.stocks.all().count()

    def __str__(self):
        return self.name

class Stock(models.Model):
    name = models.CharField(unique=True, max_length=100)
    initial_quantity = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    selling_price_retail = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    selling_price_wholesale = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    supplier = models.CharField(max_length=100, blank=True, null=True)  # optional
    stock_type = models.ForeignKey(StockType, on_delete=models.CASCADE, related_name='stocks', null=True, blank=True)  # optional

    def __str__(self):
        return self.name
    
    @property
    def sold_quantity(self):
        return sum(stockset.sold_quantity for stockset in self.stocksets.all())

    @property
    def purchased_quantity(self):
        return sum(stockset.purchased_quantity for stockset in self.stocksets.all())
    
    @property
    def sales_return_quantity(self):
        return sum(stockset.sales_return_quantity for stockset in self.stocksets.all())

    @property
    def purchases_return_quantity(self):
        return sum(stockset.purchases_return_quantity for stockset in self.stocksets.all())
    
    @property
    def remaining_quantity(self):
        return (self.initial_quantity 
                + (self.purchased_quantity - self.purchases_return_quantity) 
                - (self.sold_quantity - self.sales_return_quantity))

class StockSet(models.Model):
    name = models.CharField(unique=True, max_length=100)
    stock = models.ManyToManyField(Stock, related_name='stocksets')

    def __str__(self):
        return self.name
    
    @property
    def stock_type(self):
        if self.stock.all().count() > 1:
            return "Set"
        else:
            return self.stock.first().stock_type.name if self.stock.first().stock_type else "unknown"
    
    @property
    def unit(self):
        if self.stock.all().count() > 1:
            return ""
        else:
            return self.stock.first().stock_type.unit if self.stock.first().stock_type else ""
    
    @property
    def stock_pk(self):
        if self.stock_type == 'Set':
            return self.pk
        else:
            return self.stock.first().pk
    
    @property
    def cost_price(self):
        stocks = self.stock.all()
        if not stocks:
            return 0
        return sum(stock.cost_price for stock in stocks)
    
    @property
    def selling_price_retail(self):
        stocks = self.stock.all()
        if not stocks:
            return 0
        return sum(stock.selling_price_retail for stock in stocks)
    
    @property
    def selling_price_wholesale(self):
        stocks = self.stock.all()
        if not stocks:
            return 0
        return sum(stock.selling_price_wholesale for stock in stocks)
    
    @property
    def initial_quantity(self):
        stocks = self.stock.all()
        if not stocks:
            return 0
        return min(stock.initial_quantity for stock in stocks)
    
    @property
    def sold_quantity(self):
        return sum(sale.quantity for sale in self.sales.all())
    
    @property
    def purchased_quantity(self):
        return sum(purchase.quantity for purchase in self.purchases.all())
    
    @property
    def sales_return_quantity(self):
        return sum(sale.return_quantity for sale in self.sales.all())
    
    @property
    def purchases_return_quantity(self):
        return sum(purchase.return_quantity for purchase in self.purchases.all())
    
    @property
    def remaining_quantity(self):
        stocks = self.stock.all()
        if not stocks:
            return 0
        return min(stock.remaining_quantity for stock in stocks)
    

templates/base.html
{% load pwa %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  {% progressive_web_app_meta %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} Base {% endblock title %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/install_prompt.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block css %} {% endblock css %}
</head>

<body>

  <!-- Main navigation (Navbar) -->
  <nav>
    <div class="nav-container">
        <h2>Bismi Book Depo</h2>
        <div class="nav-links">
          <a href="{% url 'inventory' %}" class="{% if 'inventory' in request.path %}active{% endif %}">Inventory</a>
          <a href="{% url 'list_funds' %}" class="{% if '/funds/' in request.path and not '/funds/expenses/' in request.path %}active{% endif %}">Funds</a>
          <a href="{% url 'create_expense' %}" class="{% if 'expenses' in request.path %}active{% endif %}">Expense</a>
          <a href="{% url 'create_retail_view' %}" class="{% if 'retail' in request.path %}active{% endif %}">Retail</a>
          <a href="{% url 'create_wholesale_view' %}" class="{% if 'wholesale' in request.path %}active{% endif %}">Wholesale</a>
          <a href="{% url 'create_purchase_view' %}" class="{% if 'purchase' in request.path %}active{% endif %}">Purchase</a>
          <a href="{% url 'profit_report' %}" class="{% if '/reports/' in request.path and not '/reports/daybook/' in request.path %}active{% endif %}">Report</a>
          <a href="{% url 'redirect_to_selected_day_book' %}" class="{% if 'daybook' in request.path %}active{% endif %}">Day Book</a>
      </div>      
    </div>
  </nav>


  <!-- Main content area -->
  <main>
    {% block body %} {% endblock %}
  </main>

  <!-- Include JavaScript files -->
  {% block js %} {% endblock js %}

</body>

</html>

templates/model_create_edit_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ modelname }} {% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/model_create_edit_form.css' %}">
<!-- Select2 CSS -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<style>
    .table-container {
        max-width: 800px;
        margin: 20px auto;
    }
</style>
{% endblock %}

{% block body %}

{% if modelname == 'Fund' and view.object.pk == None %}
<h2 class="page-heading">{{ modelname }}s</h2>
{% else %}
<h2 class="page-heading">{{ view.object.pk|yesno:"Edit,Create" }} {{ modelname }}</h2>
{% endif %}

<div style="display: flex; justify-content: center; gap: 10px;">
    {% if modelname == 'Stock' %}
    <a href="{% url 'create_stocktype_view' %}" class="primary-button">Create Stock Type</a>
    <a href="{% url 'inventory' %}" class="primary-button">Back to Inventory</a>
    {% elif modelname == 'StockSet' %}
    <a href="{% url 'inventory' %}" class="primary-button">Back to Inventory</a>
    {% elif modelname == 'StockType' %}
    <a href="{% url 'create_stock_view' %}" class="primary-button">Back to Create Stock</a>
    {% elif modelname == 'Purchase' %}
    <a href="{% url 'list_purchase_view' %}" class="primary-button">History</a>
    <!--a href="{% url 'home' %}" class="primary-button">Back to Home</a-->
    {% elif modelname == 'Expense' %}
    <a href="{% url 'list_expense' %}" class="primary-button">List Expenses</a>
    <a href="{% url 'create_expense_type' %}" class="primary-button">Create Expense Type</a>
    <!--a href="{% url 'home' %}" class="primary-button">Back to Home</a-->
    {% elif modelname == 'Fund' %}
    {% if view.object.pk == None %}
    <!--a href="{% url 'home' %}" class="primary-button">Back to Home</a-->
    {% else %}
    <a href="{% url 'list_funds' %}" class="primary-button">Back to Fund</a>
    {% endif %}
    {% endif %}
</div>

{% if modelname == 'Fund' and view.object.pk == None %}
<div class="table-container">
    <div class="primary-table" style="grid-column: span 1;">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Balance</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for fund in funds %}
                <tr>
                    <td>{{ fund.name }}</td>
                    <td>{{ fund.current_balance }}</td>
                    <td>
                        <a href="{% url 'stockset_detail' fund.pk %}">View</a>
                        <a href="{% url 'edit_fund' fund.pk %}">Edit</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<form method="post" class="model-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endif %}

{% if modelname == 'Expense' and view.object.pk == None %}
<script>
    document.getElementById('id_amount').focus();
</script>
{% endif %}



<!-- jQuery (required by Select2) --> <!-- Select2 JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
    $(document).ready(function () {

        // select2 multi selection
        $('#id_stock').select2({
            placeholder: 'Select multiple stocks'
        });

        // select2 single selection workaround
        document.getElementById('id_stockset').multiple = true;
        $('#id_stockset').select2({
            placeholder: 'Select stocks'
        });
        document.getElementById('id_stockset').removeAttribute('multiple');

        $(document.getElementById('id_stockset')).on('change', function () {
            const self = this;
            ajaxSendRequest('/api/get_stock_cost/', { stockset_id: self.value }, function (response) {
                if (response) {
                    console.log('Callback got:', response.cost_price);
                    cost_price_tag = document.getElementById('id_price_per_unit');
                    cost_price_tag.value = response.cost_price;
                }
            });
        });
    });

    function ajaxSendRequest(endpoint, data, callback) {
        $.ajax({
            url: endpoint,
            type: 'GET',
            data: data,
            success: function (response) {
                if (callback) callback(response);
            },
            error: function (xhr, status, error) {
                console.error('Error fetching remaining quantity:', error);
                if (callback) callback(null);
            }
        });
    }
</script>


{% endblock %}